"""
Configuration settings for the stock predictor
"""

STOCK_SYMBOL = "AAPL"
UPDATE_INTERVAL_SECONDS = 2           # Changed to 2 seconds

SHORT_EMA_PERIOD = 5
LONG_EMA_PERIOD = 20
RSI_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

HISTORICAL_DAYS = 30
MAX_CANDLES_TO_KEEP = 200

PREDICTION_LOOKBACK_INTERVALS = 10    # 10 * 2 = 20 seconds evaluation
PRICE_CHANGE_THRESHOLD = 0.005

HOST = "127.0.0.1"
PORT = 8000